Repository validcube/crowdin-nested-json-postprocessor, pull requests merged in 2023-12, with the labels that each got.

#6 fix: expose input field for the GitHub Token
  README.md
  README_ACTION.md
  action.yml
Labels: P3, composite

#8 docs: update setup-python action to v5
  README.md
Labels: documentation, P5

#11 docs: remove upcoming supported status
  README.md
Labels: documentation, P3
